hydra:
  output_subdir: null  
  run:
    dir: .

defaults:
  - process: process1
  - model: model1
  - _self_

data:
  raw: data/raw/fraudTrain.csv
  processed: data/processed/processed_fraud.csv
  #final: data/final/final.csv